### ─── Authentification ────────────────────────────────────────────────────────

# 1. Créer un nouvel utilisateur
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "mathis Doe",
  "email": "mathis@example.com",
  "password": "password123"
}

###

# 2. Se connecter pour récupérer le token JWT
# Copiez la longue suite de caractères dans ("token": "...") de la réponse
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "mathis@example.com",
  "password": "password123"
}


### ─── Produits (Products) ───────────────────────────────────────────────────

# 3. Voir tous les produits (Route publique, pas besoin de token)
GET http://localhost:8080/api/products

###

# 4. Créer un produit
# REMPLACEZ <VOTRE_TOKEN> par le token obtenu à l'étape 2
POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXRoaXNAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODA1NjA2MjQsImV4cCI6MTc4MDY0NzAyNH0.mrWLePpC-tSzN4nNHVwlEw016F8wDphmjz9PPoBJKu7bkT7RpT4ttWhAdaSDLjcX_V6iVZEJOpCsLcwiKk3Fwg

{
  "name": "Super Jeu Vidéo",
  "description": "Un jeu génial",
  "price": 59.99
}
###

# 5. TEST DE SÉCURITÉ : Tenter de supprimer un produit SANS token
# (Doit retourner une erreur 401 Unauthorized ou 403 Forbidden)
DELETE http://localhost:8080/api/products/<ID_DU_PRODUIT_CREE_A_L_ETAPE_4>
Content-Type: application/json
